version: '3.9'
services:
  php-apache:
    build: 
      context: .docker/php
      dockerfile: dockerfile
    container_name: php-apache
    ports: 
      - '8000:80'
    volumes: 
    - .:/var/www/html
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    environment: 
      MARIADB_ROOT_PASSWORD: rootpass
    volumes: 
      - .docker/db:/var/lib/mysql
    ports: 
      - '3306:3306'